@startuml diagram name
!include diagram_config.puml
!include configs.puml

namespace files {
    interface ConfigManager {
        +loadConfig(): void
        +getLevelConfig(): LevelConfig
        +getPlayerConfig(): PlayerConfig
        +saveConfig(): void
    }

    class JsonConfigManager{
        +JsonConfigManager(String filePath)
        +loadConfig(): void
        +saveConfig(): void
    }

    JsonConfigManager -() ConfigManager
}

@enduml